### ISSUE TITLE
EECS2311_ comesAfter relationship

### ISSUE THREAD

**Issue by ElmiraOn** [LePa-YU/Datasets#3]
Hello, 

I was just checking the EECS2311 dataset and noticed a bug in the values in the comesAfter relationship and thought to make a note of it. the course overview view results in the following:
![image](https://user-images.githubusercontent.com/90576588/214478476-e78f9f4c-3024-4030-8230-c07205e36876.png)

as you can see the week1 instructions (and similar nodes) are not placed properly in the path. when checking the dataset I noticed there are two nodes with the same values in their comesAfter relationship (rows 7 and 20):
![image](https://user-images.githubusercontent.com/90576588/214479101-fa2aeaa2-d3bf-4575-ad11-e4b7e9eea840.png)
which results in a fork in the path. 

Note: This could affect the summative assessment view as well.

**Comment by annisiren** [comment]
Looking through the datasets to fix them and I just want to confirm how exactly we want to order things. Does it matter? Should it be iER --> aER --> rER? What if there are multiple composite ERs within the model? I can just arbitrarily pick the order within each week if it doesn't matter. Currently the logic is Module (e.g. week 1) --> comesAfter all of the ERs within the week (no order) --> (week 2)

**Comment by annisiren** [comment]
Also, quite often the comes after has relations where there are multiple aERs that come after a single iER, should these also be ordered arbitrarily? Do we need everything to be in a single line e.g. iER1 --> aER1.1 --> aER1.2 --> aER1.3 --> aER1.4 --> iER2

**Comment by biltzerpos** [comment]
Yes, the point of the comesAfter relationship is to indicate the sequencing that actually happened (or is expected to happen) in the course. Therefore, if as far as you know the order is arbitrary, then just choose one and go with it. However, you might want to consider whether composite ERs should be joined, e.g. if there is two iERs that can be done in any order, why are they not one iER?

Also, I would not include the rERs  for the comesAfter relationship. The standard view should be Start -> iER --> aER --> iER --> aER --> End. The rER just assesses the aER, it does not come after it. Most datasets do have an error in that regard (the last thing is a rubric). Let me know if you can fix this here, otherwise I'll create a separate issue.

**Comment by annisiren** [comment]
In most cases there is only one iER but there could be multiple aERs which I don't think should be combined since they have their own rubrics etc. For example you can have a homework assignment and a quiz that both come after a single iER. This order is potentially arbitrary, but I feel like they are equal in importance. Forcing them into a straight line would make it appear that this is the only order they can be done in. If that is fine, I can make the change.

**Comment by biltzerpos** [comment]
That's fine indeed.

**Comment by annisiren** [comment]
Is this still an open issue? I've changed all the datasets as we discussed, but please confirm if I missed something.

**Comment by biltzerpos** [comment]
Issue seems fixed indeed. Closing.
